### ISSUE TITLE
IOEvent callback infinite loop

### ISSUE THREAD

**Issue by dtjm** [m4rw3r/php-libev#1]
Your second example seems to enter an infinite loop on the callback. Is this how its supposed to work?

```
<?php
$loop = new libev\EventLoop();

$in = fopen('php://stdin', 'r');
$echo = new libev\IOEvent(function() use($in)
{
    // Read all (at most 200) and uppercase
    echo "ECHO: ".strtoupper(fread($in, 200));
}, $in, libev\IOEvent::READ);

$loop->add($echo);
$loop->run();
```

```
$ echo "hello" | php libevtest.php
ECHO: HELLO
ECHO: ECHO: ECHO: ECHO: ECHO: ECHO: ECHO: [....ad infinitum]
```

My setup:

```
$ php -v
PHP 5.3.8 with Suhosin-Patch (cli) (built: Sep 30 2011 05:34:36) 
Copyright (c) 1997-2011 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2011 Zend Technologies

$ php -i | grep libev
libev
libev version => 4.4
```

**Comment by m4rw3r** [comment]
Hi,

I can't confirm anything right now, but technically it is in an infinite loop; as long as there is data to read, it will print it (and there is nothing in the example removing the event, not even unrefing the file descriptor). So I guess it has something to do with how libev and PHP happens to handle EOF or whatever is triggered when a pipe ends.
I think it is probable that fread() is returning an empty string (as when reading from a socket with stream_get_line()) or false which would indicate EOF, I will look into this and correct my example so it will exit properly.

Best Regards
    Martin Wernståhl

**Comment by dtjm** [comment]
Ok thanks for the quick response and thanks for offering this open source!

**Comment by GoliathUA** [comment]
I have a problem with write event, for example

``` php
<?php

$loop = new libev\EventLoop();

$in = fopen('php://stdin', 'r');
$echo = new libev\IOEvent(function($event) use($in)
{
    echo "Write\n";

}, $in, libev\IOEvent::WRITE);

$loop->add($echo);
$loop->run();
?>
```

Script will be infinite  print "Write\n"

My setup:

```
$ php -v
PHP 5.3.2 (cli) (built: Apr  6 2010 14:08:25)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies

$ php -i | grep libev
libev
libev version => 4.4
```

How to catch event only after write to stream?

Best Regards, Denis

**Comment by m4rw3r** [comment]
Are you aware that you are checking for the possibility to write on a read-only stream?

According to a quick test in C with `select()` and `stdin`, it will always say that read-only streams are writable as long as they are open. This will in your case result in an infinite loop as `stdin` is never closed.

And in this case, even checking for write possibility on `stdout` does not make much more sense either as it will only be closed if you close the terminal window, which I'm guessing will quit the PHP process before it closes `stdout`/`stdin`/`stderr`.

It would make more sense if you attempt this on a socket, and also write some data to the socket (and don't forget to use non-blocking streams and check the return value of `fwrite()` as it will tell you if the whole message has been sent or if you need to wait a tiny bit to resend it).

**Comment by GoliathUA** [comment]
Thanks for fast answer but this problem I have with socket. Write small example:
server.php:

``` php
<?php
$server = stream_socket_server("tcp://0.0.0.0:23456", $errno, $errstr, STREAM_SERVER_BIND|STREAM_SERVER_LISTEN);
stream_set_blocking($server, 0);
$loop = libev\EventLoop::getDefaultLoop();
$base = new libev\IOEvent("onAccept", $server, libev\IOEvent::READ);
$loop->add($base);
$loop->run();

function onAccept()
{
    global $server, $loop;

    echo "onAccept".PHP_EOL;
    $client = stream_socket_accept($server);
    stream_set_blocking($client, 0);

    $event = new libev\IOEvent(function($event) use($client)
    {
        echo "Write".PHP_EOL;
    }, $client, libev\IOEvent::WRITE);

    $loop->add($event);

    //fwrite($client, "test");
}
?>
```

client.php:

``` php
<?php

$socket = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);
socket_connect($socket, "localhost", "23456");

while (true) {
    $out = socket_read($socket, 2048);
    echo $out;
}
?>
```

server.php will print endlessly "Write"

**Comment by m4rw3r** [comment]
The one reason you have the server continuously writing `"Write\n"` is that you do not write to the client socket. The client socket will only be "flagged" as unwritable when: connection has been closed or when the write buffers are full. And the stream closing must be done manually, which means that just stopping the client program will not have the server realize that the client has disconnected until it actually attempts to write and `fwrite($client, ...);` returns `int(0)`.

In your case, even if you add the `fwrite($client, "somelongstring");` inside the `$event` callback, it will not reach any of these two states, as the client will read faster than the server can write (most probably) which means that the buffer will never be full.

PHP has a default buffer size of 8 KiB, and I have not found a way which reduces or increases this on specific sockets (`stream_set_write_buffer($client, 0);` does not seem to affect it at all) which means that the server will "write" 8 KiB data and then pause until the buffer is sufficiently empty.

I suggest doing something like this:

This will make the server produce data faster than the client consumes it, which will make the server stop and only periodically write data to the client socket when the buffer is starting to get empty.

server.php:

``` php
<?php
$server = stream_socket_server("tcp://0.0.0.0:23456", $errno, $errstr, STREAM_SERVER_BIND|STREAM_SERVER_LISTEN);
stream_set_blocking($server, 0);
$loop = libev\EventLoop::getDefaultLoop();
$base = new libev\IOEvent("onAccept", $server, libev\IOEvent::READ);
$loop->add($base);
$loop->run();

function onAccept() {
    global $server, $loop;

    $client = stream_socket_accept($server);

    $event = new libev\IOEvent(function($event) use($client) {
        static $i = 0;
        $d = fwrite($client, str_repeat("a", 8*1024)); // Write PHP chunk-size large blocks
        printf("%d: wrote %d\n", $i++, $d);
        if( ! $d) $event->stop(); // Will stop on broken pipe
    }, $client, libev\IOEvent::WRITE);

    $loop->add($event);
}
```

client.php:

``` php
<?php

$socket = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);
socket_connect($socket, "localhost", "23456");
$i = 0;

while (true) {
    usleep(100000); // this wait will make the server produce faster than the client can consume
    $out = socket_read($socket, 1024*8);  // read chunk size
    printf("%d received: %d\n", $i++, strlen($out));
}
```
