### ISSUE TITLE
getting error on the start

### ISSUE THREAD

**Issue by youngvan** [m4rw3r/php-libev#3]
Can you say me what i am doing wrong?

PHP Warning:  PHP Startup: Unable to load dynamic library '/home/young/php-libev/modules/libev.so' - /home/young/php-libev/modules/libev.so: undefined symbol: event_periodic_again in Unknown on line 0

**Comment by m4rw3r** [comment]
It is strange that you get this error while I don't, as the symbol is missing even on my system. Neither my compiler nor PHP has complained about the missing symbol event_periodic_again, which is the name of a macro which I forgot to implement.

Should now be fixed with: 6b87971893c24e592d38ab238393bb177d4ac8bf

**Comment by youngvan** [comment]
still here

PHP Warning:  PHP Startup: Unable to load dynamic library '/home/young/php-libev/modules/libev.so' - /home/young/php-libev/modules/libev.so: undefined symbol: event_is_in_loop in Unknown on line 0

**Comment by m4rw3r** [comment]
I guess I really need to write a comprehensive test-suite for this, so I can be sure that it works as advertised.

I after I tested this stuff initially, I moved lots of common code into macros, and I guess I did not test it so well after that.

Btw, what compiler, OS and PHP version are you using? This might give an indication to what makes my PHP just ignore the missing symbols until the symbol is actually required.

**Comment by youngvan** [comment]
CentOS 5 64 bit 2.6.32-042stab044.11
PHP 5.4.4 (cli) (built: Jun 14 2012 18:31:18)

**Comment by m4rw3r** [comment]
cae688397740fb65c0cb2d5554d6ea567730892e fixed a typo which will resolve event_is_in_loop error.

Apparently I will probably need to use a VM in the future running an OS which does not use dyld (or whatever dynamic linker is lazily binding symbols) to test loading the extensions to prevent issues like these :/

**Comment by youngvan** [comment]
Thank's a lot! Works now!
